/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Show the signed in user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description the user the access token names */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["user"];
                    };
                };
                /** @description the access token is missing or invalid */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Show the currency, the enums and the server's today */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description the settings a client needs before its first list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["meta"];
                    };
                };
                /** @description the access token is missing or invalid */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/run_rate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Annual run rate by group
         * @description Active employees on as_of, grouped. A group with nobody active is left out. Rows are costliest first on loaded.
         */
        get: {
            parameters: {
                query?: {
                    group_by?: "department" | "country" | "level";
                    /** @description Defaults to today, and is echoed back */
                    as_of?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description the run rate */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: date */
                            as_of: string;
                            /** @enum {string} */
                            group_by: "department" | "country" | "level";
                            data: {
                                group: {
                                    /** Format: uuid */
                                    id: string;
                                    name: string;
                                };
                                /** @description Active employees on as_of */
                                headcount: number;
                                /** @description Of those, how many have a salary in force. The rest are not in the amounts. */
                                salaried: number;
                                /**
                                 * Format: int64
                                 * @description Annual salary in force on as_of
                                 */
                                gross_cents: number;
                                /**
                                 * Format: int64
                                 * @description Gross times the country's current multiplier, rounded per employee
                                 */
                                loaded_cents: number;
                            }[];
                            totals: {
                                /** @description Active employees on as_of */
                                headcount: number;
                                /** @description Of those, how many have a salary in force. The rest are not in the amounts. */
                                salaried: number;
                                /**
                                 * Format: int64
                                 * @description Annual salary in force on as_of
                                 */
                                gross_cents: number;
                                /**
                                 * Format: int64
                                 * @description Gross times the country's current multiplier, rounded per employee
                                 */
                                loaded_cents: number;
                            };
                        };
                    };
                };
                /** @description the access token is missing or invalid */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
                /** @description group_by or as_of is invalid */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/employees/{employee_id}/audits": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                employee_id: string;
            };
            cookie?: never;
        };
        /**
         * List who changed an employee, and their salary revisions, and when
         * @description Newest first. Covers the employee's own changes and every change to their salary revisions.
         */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    /** @description Above 100 is clamped to 100, not refused */
                    per_page?: number;
                };
                header?: never;
                path: {
                    employee_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description a page of the trail */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["audit"][];
                            pagination: components["schemas"]["pagination"];
                        };
                    };
                };
                /** @description the access token is missing or invalid */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
                /** @description no employee has that id */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
                /** @description page or per_page is not a positive integer */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/sign_in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange credentials for a token pair */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                        password: string;
                    };
                };
            };
            responses: {
                /** @description signed in */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["token_pair"];
                    };
                };
                /** @description a credential is missing */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
                /** @description the email or the password is wrong */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate a refresh token for a new pair */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        refresh_token: string;
                    };
                };
            };
            responses: {
                /** @description rotated, and the old refresh token is now dead */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["token_pair"];
                    };
                };
                /** @description no refresh token */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
                /** @description the refresh token is expired or has already been used */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/sign_out": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete every refresh token for the signed in user */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description signed out */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description the access token is missing or invalid */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/countries/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update a country's employer cost multiplier
         * @description Only the multiplier is editable. Every fully loaded figure uses the current value, past dates included.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * @description Above 0, below 100, at most 4 decimal places
                         * @example 1.45
                         */
                        employer_cost_multiplier?: string;
                    };
                };
            };
            responses: {
                /** @description updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["country"];
                    };
                };
                /** @description the access token is missing or invalid */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
                /** @description no country has that id */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
                /** @description the multiplier is invalid */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/v1/employees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List employees
         * @description Search, filter, sort and pagination all run on the server.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Part of the name, email or title, ignoring case. A whole UUID matches the id instead. */
                    q?: string;
                    "department_id[]"?: string[];
                    "country_id[]"?: string[];
                    "level_id[]"?: string[];
                    /** @description The whole title */
                    title?: string;
                    /** @description As of as_of */
                    status?: "pending" | "active" | "exited";
                    /** @description A leading - sorts descending. salary and exit_date put nulls last either way. */
                    sort?: "name" | "-name" | "hire_date" | "-hire_date" | "exit_date" | "-exit_date" | "salary" | "-salary" | "department" | "-department" | "country" | "-country" | "level" | "-level";
                    /** @description Defaults to today. Status and current_salary are computed for this date, and it is echoed back. */
                    as_of?: string;
                    page?: number;
                    /** @description Above 100 is clamped to 100, not refused */
                    per_page?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description a page of employees */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["employee"][];
                            pagination: components["schemas"]["pagination"];
                        };
                    };
                };
                /** @description the access token is missing or invalid */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
                /** @description a filter, sort, as_of, page or per_page is invalid */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
            };
        };
        put?: never;
        /** Create an employee */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name: string;
                        /** Format: email */
                        email: string;
                        /** @description Free text. GET /api/v1/titles offers the ones already in use. */
                        title: string;
                        /** Format: date */
                        hire_date: string;
                        /** Format: date */
                        exit_date?: string | null;
                        /** Format: uuid */
                        country_id: string;
                        /** Format: uuid */
                        department_id: string;
                        /** Format: uuid */
                        level_id: string;
                    };
                };
            };
            responses: {
                /** @description created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["employee"];
                    };
                };
                /** @description the access token is missing or invalid */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
                /** @description an attribute is invalid, or the email is already in use */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/employees/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Show an employee */
        get: {
            parameters: {
                query?: {
                    /** @description Defaults to today. Status and current_salary are computed for this date, and it is echoed back. */
                    as_of?: string;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description the employee */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["employee"];
                    };
                };
                /** @description the access token is missing or invalid */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
                /** @description no employee has that id */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
                /** @description as_of is not a date */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update an employee
         * @description Send only the attributes that change. A null exit_date clears it.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name?: string;
                        /** Format: email */
                        email?: string;
                        /** @description Free text. GET /api/v1/titles offers the ones already in use. */
                        title?: string;
                        /** Format: date */
                        hire_date?: string;
                        /** Format: date */
                        exit_date?: string | null;
                        /** Format: uuid */
                        country_id?: string;
                        /** Format: uuid */
                        department_id?: string;
                        /** Format: uuid */
                        level_id?: string;
                    };
                };
            };
            responses: {
                /** @description updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["employee"];
                    };
                };
                /** @description the access token is missing or invalid */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
                /** @description no employee has that id */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
                /** @description an attribute is invalid */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/v1/countries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List countries
         * @description A closed set, returned whole and unpaginated.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description every country */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["country"][];
                        };
                    };
                };
                /** @description the access token is missing or invalid */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/departments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List departments
         * @description A closed set, returned whole and unpaginated.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description every department */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["department"][];
                        };
                    };
                };
                /** @description the access token is missing or invalid */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/levels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List levels
         * @description A closed set, returned whole and unpaginated.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description every level */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["level"][];
                        };
                    };
                };
                /** @description the access token is missing or invalid */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/employees/{employee_id}/salary_revisions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                employee_id: string;
            };
            cookie?: never;
        };
        /**
         * List an employee's salary history
         * @description Live revisions, newest first, each with the amount in force before it. Voided ones are left out.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    employee_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description the history */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["salary_history_entry"][];
                        };
                    };
                };
                /** @description the access token is missing or invalid */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
                /** @description no employee has that id */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Add a salary revision
         * @description A raise is a new revision, never an edit. The response carries the revision in force before it, so a form can show the change without a second request. A backdated revision also changes the previous amount of the one after it, so reload the history rather than patching a row.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    employee_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * Format: int64
                         * @description The new annual salary, in minor units
                         */
                        amount_cents: number;
                        /**
                         * Format: date
                         * @description May be in the future. Must fall inside the employment.
                         */
                        effective_date: string;
                        /** @enum {string} */
                        reason: "merit" | "promotion" | "market_adjustment" | "correction";
                        note?: string | null;
                    };
                };
            };
            responses: {
                /** @description created, with the revision it follows */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["salary_change"];
                    };
                };
                /** @description the access token is missing or invalid */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
                /** @description no employee has that id */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
                /** @description an attribute is invalid, or a live revision already has that date */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/employees/{employee_id}/salary_revisions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                employee_id: string;
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Void a salary revision
         * @description The row is kept with voided_at set, and drops out of every read. Voiding twice is a no-op.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    employee_id: string;
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description voided */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description the access token is missing or invalid */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
                /** @description no revision with that id belongs to this employee */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /**
         * Correct a salary revision
         * @description For fixing a mistake. A raise is a new revision. A voided revision cannot be edited.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    employee_id: string;
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * Format: int64
                         * @description The new annual salary, in minor units
                         */
                        amount_cents?: number;
                        /**
                         * Format: date
                         * @description May be in the future. Must fall inside the employment.
                         */
                        effective_date?: string;
                        /** @enum {string} */
                        reason?: "merit" | "promotion" | "market_adjustment" | "correction";
                        note?: string | null;
                    };
                };
            };
            responses: {
                /** @description corrected */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["salary_revision"];
                    };
                };
                /** @description the access token is missing or invalid */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
                /** @description no revision with that id belongs to this employee */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
                /** @description an attribute is invalid */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/v1/titles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Suggest titles already in use
         * @description For the title typeahead. Distinct titles with how many employees ever held them, most used first, capped at 20. It truncates rather than paginates.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Matches anywhere in the title, ignoring case */
                    q?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description the most used matching titles */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["title_count"][];
                        };
                    };
                };
                /** @description the access token is missing or invalid */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness: the process is up and Postgres answers */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description healthy */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status: "ok" | "unavailable";
                            /** @enum {string} */
                            database: "ok" | "unreachable";
                        };
                    };
                };
                /** @description Postgres did not answer */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status: "ok" | "unavailable";
                            /** @enum {string} */
                            database: "ok" | "unreachable";
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness: liveness plus no pending migrations */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ready */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status: "ok" | "unavailable";
                            /** @enum {string} */
                            database: "ok" | "unreachable";
                            /** @enum {string} */
                            migrations: "ok" | "pending" | "unknown";
                        };
                    };
                };
                /** @description a migration is pending, or Postgres did not answer */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status: "ok" | "unavailable";
                            /** @enum {string} */
                            database: "ok" | "unreachable";
                            /** @enum {string} */
                            migrations: "ok" | "pending" | "unknown";
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        token_pair: {
            access_token: string;
            /** @description Seconds the access token stays valid */
            expires_in: number;
            refresh_token: string;
        };
        error: {
            error: {
                code: string;
                message: string;
                details: {
                    field: string;
                    message: string;
                }[];
            };
        };
        pagination: {
            total: number;
            page: number;
            /** @description The page size used, after clamping to 100 */
            per_page: number;
            total_pages: number;
            /** @description Null on the first page. Past the end it is the last real page. */
            prev_page: number | null;
            /** @description Null on the last page */
            next_page: number | null;
        };
        user: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: email */
            email: string;
        };
        meta: {
            /** @example USD */
            base_currency: string;
            /** @description Decimal places in an amount: amount_cents / 10^minor_unit */
            minor_unit: number;
            /**
             * Format: date
             * @description The as_of a request gets when it omits the parameter
             */
            today: string;
            employee_statuses: string[];
            salary_revision_reasons: string[];
        };
        country: {
            /** Format: uuid */
            id: string;
            /** @example IN */
            code: string;
            name: string;
            /**
             * @description A decimal string, so the client never holds it as a float. Gross times this is fully loaded.
             * @example 1.45
             */
            employer_cost_multiplier: string;
        };
        department: {
            /** Format: uuid */
            id: string;
            name: string;
        };
        level: {
            /** Format: uuid */
            id: string;
            /** @example L4 */
            code: string;
            name: string;
            /** @description Orders levels. Sort on this, never on the code. */
            rank: number;
        };
        employee: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: email */
            email: string;
            title: string;
            /** Format: date */
            hire_date: string;
            /**
             * Format: date
             * @description Inclusive: the employee is active and paid that day
             */
            exit_date: string | null;
            /**
             * @description Derived from the dates, as of as_of
             * @enum {string}
             */
            status: "pending" | "active" | "exited";
            /**
             * Format: date
             * @description The date status and current_salary were computed for
             */
            as_of: string;
            country: components["schemas"]["country"];
            department: components["schemas"]["department"];
            level: components["schemas"]["level"];
            /** @description The live revision in force on as_of. Null unless the employee is active that day. */
            current_salary: {
                /**
                 * Format: int64
                 * @description Minor units of the base currency
                 */
                amount_cents: number;
                /** Format: date */
                effective_date: string;
            } | null;
        };
        salary_revision: {
            /** Format: uuid */
            id: string;
            /**
             * Format: int64
             * @description Minor units of the base currency
             */
            amount_cents: number;
            /** Format: date */
            effective_date: string;
            /** @enum {string} */
            reason: "merit" | "promotion" | "market_adjustment" | "correction";
            note: string | null;
            /** Format: date-time */
            voided_at: string | null;
        };
        salary_history_entry: {
            /** Format: uuid */
            id: string;
            /**
             * Format: int64
             * @description Minor units of the base currency
             */
            amount_cents: number;
            /** Format: date */
            effective_date: string;
            /** @enum {string} */
            reason: "merit" | "promotion" | "market_adjustment" | "correction";
            note: string | null;
            /** Format: date-time */
            voided_at: string | null;
            /**
             * Format: int64
             * @description The live amount in force the day before, null for the first revision
             */
            previous_amount_cents: number | null;
        };
        salary_change: {
            /** Format: uuid */
            id: string;
            /**
             * Format: int64
             * @description Minor units of the base currency
             */
            amount_cents: number;
            /** Format: date */
            effective_date: string;
            /** @enum {string} */
            reason: "merit" | "promotion" | "market_adjustment" | "correction";
            note: string | null;
            /** Format: date-time */
            voided_at: string | null;
            /**
             * Format: int64
             * @description The live amount in force the day before, null for the first revision
             */
            previous_amount_cents: number | null;
            /** Format: date */
            previous_effective_date: string | null;
        };
        audit: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            action: "create" | "update" | "destroy";
            /** @enum {string} */
            auditable_type: "employee" | "salary_revision";
            /** Format: uuid */
            auditable_id: string;
            /** @description On create, each attribute's value. On update, each changed attribute as [old, new]. */
            audited_changes: {
                [key: string]: unknown;
            };
            /** @description Who made the change. Null outside a signed in request. */
            user: {
                /** Format: uuid */
                id: string;
                name: string;
                /** Format: email */
                email: string;
            } | null;
            /** Format: date-time */
            created_at: string;
        };
        title_count: {
            title: string;
            employee_count: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
